<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsExcel" Version="0.0.49" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.300" />
  </ItemGroup>

</Project>
